# Generated by Django 4.2.3 on 2023-07-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('wallet', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Кошелёк')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'unique_together': {('full_name', 'inn')},
            },
        ),
    ]
