# Generated by Django 4.2.3 on 2023-08-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set(),
        ),
    ]
